FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.1-sdk AS build
RUN apt-get update -yq && apt-get upgrade -yq && apt-get install -yq curl git nano
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - && apt-get install -yq nodejs build-essential
RUN npm install -g npm
RUN npm install
WORKDIR /src
COPY ["StealthMonitoring.NasaImages.WebApp/StealthMonitoring.NasaImages.WebApp.csproj", "StealthMonitoring.NasaImages.WebApp/"]
COPY ["StealthMonitoring.Storage/StealthMonitoring.Storage.csproj", "StealthMonitoring.Storage/"]
RUN dotnet restore "StealthMonitoring.NasaImages.WebApp/StealthMonitoring.NasaImages.WebApp.csproj"
COPY . .
WORKDIR "/src/StealthMonitoring.NasaImages.WebApp"
RUN dotnet build "StealthMonitoring.NasaImages.WebApp.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "StealthMonitoring.NasaImages.WebApp.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "StealthMonitoring.NasaImages.WebApp.dll"]